# Generated by Django 4.1.7 on 2023-03-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("hr", "Кадровик"),
                    ("staff", "Сотрудник"),
                    ("unknown", "Посетитель"),
                ],
                default="unknown",
                max_length=8,
            ),
        ),
    ]
