# Generated by Django 4.1.7 on 2023-02-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Компания", "verbose_name_plural": "Компании"},
        ),
        migrations.AddField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=20, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                null=True, upload_to="logo/", verbose_name="Логотип"
            ),
        ),
    ]
