# Generated by Django 4.1.7 on 2023-02-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="created",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="slug",
            field=models.SlugField(
                default="Старая вакансия", verbose_name="Краткое описание"
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("open", "Окрытая"),
                    ("closed", "Закрытая"),
                ],
                default="draft",
                max_length=10,
                verbose_name="Статус вакансии",
            ),
        ),
    ]
