# Generated by Django 4.1.7 on 2023-02-18 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vacancies", "0002_vacancy_created_vacancy_slug_vacancy_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancy",
            options={
                "ordering": ["text"],
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
        migrations.AddField(
            model_name="vacancy",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
