# Generated by Django 4.1.7 on 2023-03-02 06:19

from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0002_vacancy_min_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="date_published",
            field=models.DateField(
                null=True, validators=[vacancies.models.chek_date_created]
            ),
        ),
    ]
