# Generated by Django 4.1.7 on 2023-02-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0004_skill_vacancy_skills"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancy",
            options={"verbose_name": "Вакансия", "verbose_name_plural": "Вакансии"},
        ),
        migrations.AddField(
            model_name="skill",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
